mapa_romania = {
    'Arad': {'conexoes': [{'cidade': 'Zerind', 'distancia': 75},
                          {'cidade': 'Timisoara', 'distancia': 118},
                          {'cidade': 'Sibiu', 'distancia': 140}]},
    'Sibiu': {'conexoes': [{'cidade': 'Fagaras', 'distancia': 99},
                           {'cidade': 'Rimnicu Vilcea', 'distancia': 80},
                           {'cidade': 'Oradea', 'distancia': 151},
                           {'cidade': 'Arad', 'distancia': 140}]},
    'Fagaras:': {'conexoes': [{'cidade': 'Bucharest', 'distancia': 211},
                              {'cidade': 'Sibiu', 'distancia': 99}]},
    'Rimnicu Vilcea': {'conexoes': [{'cidade': 'Craiova', 'distancia': 146},
                                    {'cidade': 'Sibiu', 'distancia': 80},
                                    {'cidade': 'Pitesti', 'distancia': 97}]},
    'Pitesti': {'conexoes': [{'cidade': 'Bucharest', 'distancia': 101},
                             {'cidade': 'Rimnicu Vilcea', 'distancia': 97},
                             {'cidade': 'Craiova', 'distancia': 138}]},
    'Bucharest': {'conexoes': [{'cidade': 'Fagaras', 'distancia': 211},
                               {'cidade': 'Pitesti', 'distancia': 101},
                               {'cidade': 'Urziceni', 'distancia': 85},
                               {'cidade': 'Giurgiu', 'distancia': 90}]},
    'Giurgiu': {'conexoes': [{'cidade': 'Bucharest', 'distancia': 90}]},
    'Urziceni': {'conexoes': [{'cidade': 'Bucharest', 'distancia': 85},
                              {'cidade': 'Vaslui', 'distancia': 142},
                              {'cidade': 'Hirsova', 'distancia': 98},
                              ]},
    'Hirsova': {'conexoes': [{'cidade': 'Urziceni', 'distancia': 98},
                             {'cidade': 'Eforie', 'distancia': 86}]},
    'Eforie': {'conexoes': [{'cidade': 'Hirsova', 'distancia': 86}]},
    'Vaslui': {'conexoes': [{'cidade': 'Urziceni', 'distancia': 142},
                            {'cidade': 'Iasi', 'distancia': 92}]},
    'Iasi': {'conexoes': [{'cidade': 'Neamt', 'distancia': 87},
                          {'cidade': 'Vaslui', 'distancia': 92}]},
    'Neamt': {'conexoes': [{'cidade': 'Iasi', 'distancia': 87}]},
    'Craiova': {'conexoes': [{'cidade': 'Pitesti', 'distancia': 138},
                             {'cidade': 'Rimnicu Vilcea', 'distancia': 146},
                             {'cidade': 'Drobeta', 'distancia': 120}]},
    'Drobeta': {'conexoes': [{'cidade': 'Craiova', 'distancia': 120},
                             {'cidade': 'Mehadia', 'distancia': 75}]},
    'Mehadia': {'conexoes': [{'cidade': 'Drobeta', 'distancia': 75},
                             {'cidade': 'Lugoj', 'distancia': 70}]},
    'Lugoj': {'conexoes': [{'cidade': 'Mehadia', 'distancia': 70},
                           {'cidade': 'Timisoara', 'distancia': 111}]},
    'Timisoara': {'conexoes': [{'cidade': 'Arad', 'distancia': 118},
                               {'cidade': 'Lugoj', 'distancia': 111}]},
    'Zerind': {'conexoes': [{'cidade': 'Arad', 'distancia': 75},
                            {'cidade': 'Oradea', 'distancia': 71}]},
    'Oradea': {'conexoes': [{'cidade': 'Zerind', 'distancia': 71},
                            {'cidade': 'Sibiu', 'distancia': 151}]}
}

heuristica_romania = {
    'Arad': 366,
    'Bucharest': 0,
    'Craiova': 160,
    'Drobeta': 242,
    'Eforie': 161,
    'Fagaras': 176,
    'Giurgiu': 77,
    'Hirsova': 151,
    'Iasi': 226,
    'Lugov': 244,
    'Mehadia': 241,
    'Neamt': 234,
    'Oradea': 380,
    'Pitesti': 100,
    'Rimnicu Vilcea': 193,
    'Sibiu': 253,
    'Timisoara': 329,
    'Urziceni': 80,
    'Vaslui': 199,
    'Zerind': 374,
}


def romania_astar():
    print(mapa_romania.__len__())
